ecommerce/cart/urls.py
from cart import views
from django.urls import path,include
app_name='cart'
urlpatterns = [
    path('cart/<n>',views.cart,name="cart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<n>',views.cart_remove,name="cart_remove"),
    path('cart_delete/<n>',views.cart_delete,name="cart_delete"),
    path('orderform', views.orderform, name="orderform"),
    path('orderview', views.orderview, name="orderview"),

]

ecommerce/design/design/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('',include('cart.urls')),

]

ecommerce/search/urls.py
from search import views
from django.urls import path,include
app_name='search'
urlpatterns = [


  path('',views.search,name="search")

]

ecommerce/shop/urls.py
from shop import views
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
app_name='shop'

urlpatterns = [
    path('',views.allcategories,name="allcategories"),
    path('allprod/<p>',views.allproducts,name="allprod"),
    path('details/<p>',views.details,name="details"),
    path('register',views.register,name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product

# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name


    def subtotal(self):
        return self.quantity*self.product.price


class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    ordered_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    acctype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart,Account,Order
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def cartview(request):
    total=0
    u=request.user
    cart=Cart.objects.filter(user=u)
    for i in cart:
        total+=i.quantity*i.product.price

    return render(request,'cart.html',{'c':cart,'total':total})


@login_required
def cart(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock > 0):
             cart.quantity+=1
             cart.save()
             p.stock-=1
             p.save()
    except:
        if(p.stock>0):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock-=1
            p.save()


    return cartview(request)

@login_required
def cart_remove(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity>1):
             cart.quantity-=1
             cart.save()
             p.stock+=1
             p.save()
        else:
            cart.delete()
            p.stock+=1
            p.save()

    except:
        pass
    return cartview(request)

@login_required
def cart_delete(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)

        cart.delete()
        p.stock+=cart.quantity
        p.save()

    except:
        pass
    return cartview(request)
@login_required
def orderform(request):
    if request.method=="POST":
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']

        u=request.user
        cart=Cart.objects.filter(user=u)

        total=0
        for i in cart:
            total+=i.quantity*i.product.price

        try:
            ac=Account.objects.get(acctnum=n)
            if(ac.amount >= total):
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                    o.save()
                cart.delete()
                msg="Your Order placed successfully"
                return render(request,'orderdetail.html',{'msg':msg})
            else:
                msg="insufficient balance"
                return render(request,'orderdetail.html',{'msg':msg})
        except:
            pass


    return render(request,'orderform.html')

@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)

    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

# Create your views here.
def search(request):
    b=None
    q=""
    if (request.method=="POST"):
        q=request.POST['q']
        if q:
           b=Product.objects.filter(Q(name__icontains=q)| Q(desc__icontains=q))
    return render(request,'search.html',{'q':q,'b':b})

ecommerce/templates/base.html
<!DOCTYPE html>
hello world
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">

</head>
<body>

<header><center><br>
    <img src="{% static 'images/d2.jpg' %}" height="100px" width="100px"></center><br>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MY SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcategories' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {%  for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allprod' i.name %}">{{i.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
          {% if user.is_authenticated %}
                                            <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% if user.is_superuser == False %}


                        <li class="nav-item">
          <a class="nav-link active fs-5" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i><sup class="ms-1">{{count}}</sup></a>
        </li>
                                  <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>
          {% endif %}
          {% else %}
                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
          {% endif %}


      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}
{% endblock %}

<footer>
  <div class="x">
        <p><b><i class="fa-sharp fa-solid fa-copyright"></i>Myshop Pvt ltd.All Rights Reserved</b></p>
  </div>
</footer>

</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>

<h2>My Cart</h2></center><br>

<div class="container">
    <div class="row">
        <div class="col-8" style="margin-bottom:100px">
            <table class="table table-bordered">
                <tr><th> Cart Items</th></tr>

                {% for i in c %}
                <tr><td>
                    <img src="{{i.product.image.url}}" height="150px" width="150px">
                </td>
                <td>{{i.product.name}}</td>
                    <td><h6>Product Id:{{i.product.id}}</h6>
                        <h6>Price:{{i.product.price}}</h6>
                        <h6>Quantity:{{i.quantity}}*{{i.product.price}}</h6></td>
                    <td>Subtotal:{{i.subtotal}}</td>
                    <td>
                        {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:cart' i.product.name %}"><i class="fa-solid fa-plus text-secondary fs-5"></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-minus text-secondary fs-5"></i></a>
                    <a href="{% url 'cart:cart_delete' i.product.name %}"><i class="fa-solid fa-trash text-secondary fs-5"></i></a>
                    </td>
                    {% else %}

                    <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-minus text-secondary fs-5"></i></a>
                    <a href="{% url 'cart:cart_delete' i.product.name %}"><i class="fa-solid fa-trash text-secondary fs-5"></i></a>
                    {% endif %}

                </tr>
                {% endfor %}

            </table>


        </div>
        <div class="col-4" style="position:relative;">
            <table class="table table-bordered">
                <tr><th colspan="5">Check Out</th></tr>
                <tr><td>TOTAL :{{total}}</td></tr>

            </table>
            <a href="{% url 'cart:orderform' %}" class="btn btn-danger" style="position:absolute;left:10px;">Place order</a>
            <a href="{% url 'shop:allcategories' %}" class="btn btn-danger" style="position:absolute;right:10px;">Continue shopping</a>

        </div>

    </div>
</div>

{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/d10.jpg' %}" height="450" width="100%">

</div>

<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">OUR COLLECTIONS</h3>
    <p style="text-align:justify; line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

</p>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
    {% for i in c %}
    <div class="col-sm-4">
    <div class="card" style="width: 26rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title text-center fw-bold">{{i.name}} </h5>
    <a href="{% url 'shop:allprod' i.name %}" class="btn btn-primary" style="position:relative;left:38%;">Products </a>
  </div>
</div>
        </div>
        {% endfor %}
</div>
</div>




{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5" style="margin-bottom:100px;">
<div class="row">

    <div class="col-sm-4 me-5">
        <img src="{{c.image.url}}" height="300px" width="350px">
    </div>
    <div class="col-sm-6 me-5">
        <h3>{{c.name}}</h3>
                <p class="mt-2 lh-base" style="text-align:justify">{{c.desc}}</p>
                <h3 class="mt-2">{{c.price}}</h3>
        {{c.stock}}
        {% if user.is_superuser == True %}
        {% if c.stock == 0 %}
        <h3>out of stock</h3>
         <a href="{% url 'admin:index' %}" class="btn btn-danger mt-3">ADD STOCK</a>
        {% else %}
        <h3>product in stock</h3>
         <a href="{% url 'admin:index' %}" class="btn btn-danger mt-3">ADD STOCK</a>
        {% endif %}


        {% else %}
        {% if c.stock == 0 %}
         <h3>out of stock</h3>
        {% else %}
        <a href="{% url 'cart:cart' c.name %}" class="btn btn-danger mt-3">ADD TO CART</a>
        {% endif %}
{% endif %}

    </div>
</div>
</div>




{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="container" style="margin-bottom:100px">

<h2>Login page</h2>
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u"  placeholder="enter username">
</div>
<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="enter password">
</div>
            <div class="mb-3">

  <input type="submit" class="form-control btn btn-secondary">
    </div>
</form></div></center>


    {% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
<h3 class="text-center text-success">{{msg}}</h3>
    <h3 class="text-center text-danger">Thank You</h3>
    <h3 class="text-center"><a href="{% url 'shop:allcategories' %}">Continue Shopping</a></h3>
    </div>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div class="container" style="margin-bottom:100px">
<h3>Order Form</h3>

<form method="POST">

    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Addresss</label>
    <input type="text" class="form-control" name="a"  placeholder="enter address">
</div>
<div class="mb-3">
  <label  class="form-label">Phone</label>
  <input type="number" class="form-control" name="p"  placeholder="enter phone number">
</div>
    <div class="mb-3">
  <label  class="form-label">Account Number</label>
  <input type="number" class="form-control" name="n"  placeholder="enter account number">
</div>
            <div class="mb-3">

  <input type="submit" class="form-control btn btn-secondary">
    </div>
</form>
    </div>
</center>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h2>My Orders</h2>
</center>
<div class="container">
    <div class="row mt-5 border border-1">
        <h4 class="text-dark">Name of the customer:{{u}}</h4>
                {% for i in o %}
        <div class="col-sm-4 mt-3" style="margin-left:100px;">
            <img src="{{i.product.image.url}}" height="200px" width="200px">
        </div>
        <div class="col-sm-6 text-center mt-3">
            <b>Product name:{{i.product.name}}</b><br>
                        <b>Product price:{{i.product.price}}</b><br>
                        <b>Delivery_address:{{i.address}}</b><br>
                        <b>Product name:{{i.product.name}}</b><br>
                        <b>Customer phone:{{i.phone}}</b><br>
                        <b>Ordered on:{{i.ordered_date}}</b><br>
                        <b class="text-success">Delivery_status:{{i.delivery_status}}</b><br>






        </div>
        {% endfor %}
    </div>

</div>



{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{{c.image.url}}" height="450" width="100%">

</div>

<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">{{c.name}} </h3>
    <p style="text-align:justify; line-height:2;">{{c.desc}}

</p>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
    {% for i in p %}
    <div class="col-sm-4">
    <div class="card" style="width: 26rem;">
  <img src="{{i.image.url}}" height="250px" width="100%" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title text-center fw-bold">{{i.name}} </h5>
          <h5 class="card-title text-center fw-bold">{{i.price}} </h5>

    <a href="{% url 'shop:details' i.name %}" class="btn btn-primary" style="position:relative;left:40%;">Details </a>
  </div>
</div>
        </div>
        {% endfor %}
</div>
</div>


{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<div class="container" style="margin-bottom:100px">
<h2>Register page</h2><br>
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u"  placeholder="enter username">
</div>
<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p"  placeholder="enter password">
</div>

    <div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="cp" placeholder="enter password">
    </div>

        <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="text" class="form-control" name="e">
    </div>


        <div class="mb-3">
  <label  class="form-label">First Name</label>
  <input type="text" class="form-control" name="f">
    </div>

            <div class="mb-3">
  <label  class="form-label">Last Name</label>
  <input type="text" class="form-control" name="l">
    </div>




        <div class="mb-3">

  <input type="submit" class="form-control btn btn-secondary">
    </div>
    </form></div></center>





{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div><center>
<h2> You Have Searched  {{q}}</h2></center>
</div><br>


<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
{% if b %}
    {% for i in b %}
    <div class="col-sm-4">
    <div class="card" style="width: 26rem;">
  <img src="{{i.image.url}}" height="250px" width="100%" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title text-center fw-bold">{{i.name}} </h5>
          <h5 class="card-title text-center fw-bold">{{i.price}} </h5>

    <a href="{% url 'shop:details' i.name %}" class="btn btn-primary" style="position:relative;left:40%;">Details </a>
  </div>
</div>
        </div>{% endfor %}
{% else %}
        <h4 class="text-center">No Result</h4>
{% endif %}
</div>
</div>


{% endblock %}